### ISSUE TITLE
What editor(s) do you use?

### ISSUE THREAD

**Issue by benlk** [danielbachhuber/ama#1]
And do you use any language-specific extensions or tools to supplement your editor?

**Comment by danielbachhuber** [comment]
I primarily use Sublime Text 3 with these packages:

* API Blueprint
* ApplySyntax
* Babel
* Color Highlighter
* EditorConfig
* EJS 2
* Markdown Extended
* SCSS
* SublimeLinter
* SublimeLinter-php
* Theme - Cobalt 2
* TrailingSpaces

I also use vim on remote machines, or when I need to quickly edit a file. I tried switching entirely to vim (and lasted three weeks), but it was too much of a productivity hit. I also tried Atom, but I far prefer native apps than the HTML/CSS/JS on the desktop thing.

Yourself?

**Comment by benlk** [comment]
Primarily vim, with [this vimrc](https://github.com/benlk/dotfiles/blob/master/.vimrc) and [rainbow parentheses](https://github.com/luochen1990/rainbow/). I'm planning to try out the [phpCS](https://github.com/vim-scripts/phpcs.vim) script sometime soon but mostly do my linting by hand.

I'll occasionally use TextEdit on OSX or gEdit on Linux as a clipboard, or nano if vim isn't on the remote machine.

HTML/CSS/JS on the desktop does seem kinda weird, and was why I hadn't really looked into Atom. I used to use Brackets: its PHP support was sad. Komodo was very, very bloated at the time (~2 years ago) that I tried it.

**Comment by danielbachhuber** [comment]
Sweet!
