### ISSUE TITLE
If you had $1,800,500 - what would you do with it?

### ISSUE THREAD

**Issue by JustinSainton** [danielbachhuber/ama#4]
Requirements: Imagine that your mortgage/debts were paid off, retirement was funded, kids had college paid for, etc.

**Comment by danielbachhuber** [comment]
That's a tough question.

The first thought that comes to mind is investing the money in things that don't have a direct financial return. For instance, there's a [greenway trail in Tualatin](https://www.tualatinoregon.gov/communityservices/tualatin-river-greenway-trail-project) that will be extended as they have the financial means. Tualatin is also in the [America's Best Communities competition](https://americasbestcommunities.com/meet-the-communities/5597/), and wants to build a community center with the money if they win. Or, put the money towards a societal ail (e.g. homeless shelter, etc.). 

I think I would be predisposed to investing the money in my local community, though. It probably reflects where I am in life.

How about yourself?

**Comment by JustinSainton** [comment]
Mmm, I love that your answers revolve around making your local community a better place for all. A++

> How about yourself?

Assuming all the same things as above, I'd split the funds in three ways (UPDATE: OMG, sorry for the blog post.):

### Selfish ($540,000)

This is probably a little ridiculous (and we're already doing this to a much less expensive degree) - but I'd likely take about $30K/year for the next 18 years and spend it on a few significant trips each year to go somewhere globally as a family. We have friends who are missionaries in Africa, Europe, the Philippines, Asia, etc. Exposing them to the real world - not just the upper-middle-class-white-American-Christian version they're growing up with - is really important to me.  Helping them learn to deal with really hard emotional things at a young age is important to us. 

For example, on one trip, we might take them to our friend's in Tanzania who help young moms (12 - 16 years old) through childbirth and birth/sex education. They'd likely be exposed to the beauty of newborn life and the sadness of maternal and infant death.  And on the other side of a trip like that, we'd maybe spend a week in Cape Town or do something to really build internal relationship within our own family and have fun.

Even with our basketball team of a family, we could easily do three trips a year like this, for ~3 weeks at a time, within that budget.

### Local Investment ($600,500)

Loved everything you said here.  We're moving to Newberg in a couple months - it's where I spent a lot of time growing up, and my kids will likely do much of their growing up there.  

- Would invest ~250K in launching something like [PIE](http://www.piepdx.com/), but for the valley. Something that would be a combination between an investment fund/co-working space. I'm a part of some local business groups for young professionals and I'd love to invest in the vision some of them have to grow their own businesses or start new ones.
- Yamhill County has a pretty significant homeless community, and that's something I feel pretty passionately about. I think it's a solvable problem, [and others agree](http://www.yamhillcap.org/community-outreach/homeless-count/).  I think there are great things people are doing at a governmental level to assess and address this situation - but I think if we were able to invest in creative solutions and pull people together from areas (businesses, mainly - but also civic, faith-based, etc.) to take some radical measures. I think it's probably a $3-5MM problem, with the right thinking.  I'd want to invest about 350K into being a part of that solution.
- With the remaining $500 - I'd probably just give it away :) Totally recklessly.  

### Global Investment ($660,000)

When I think too much about the impact we can have in the world at the global level, it gets overwhelming. Do you go with Kiva or Charity:water? Do you give to NGOs or faith-based? Do you care more about efficiency or impact?

For me - I favor impact over efficiency. While I value transparency, efficiency and accountability - all important - I think it's really easy to be transparent, accountable and efficient in doing things that ultimately don't have the desired impact.  To that end, I'd likely spend a lot of my time on our "Selfish" pursuits investigating different organizations in different areas of the world that would be considered outliers with regards to their impact, and invest a lot in a small number of those.  

Finding 2-3 organizations that we could invest between $220,000 and $330,000 in would be pretty rad.

**Comment by danielbachhuber** [comment]
Sounds like we should fine some money :)
